apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
  namespace: default
  labels:
    app: devops-cicd-app
spec:
  type: LoadBalancer
  selector:
    app: devops-cicd-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 3000
    path: /metrics
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
